# Generated by Django 4.2.7 on 2023-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Semesters',
                'ordering': ['-semester'],
            },
        ),
    ]
