# Generated by Django 4.2.7 on 2023-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='semesters', to='course.course'),
        ),
    ]
