# Generated by Django 4.2.7 on 2023-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbtbk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='dept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='sid',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
