# Generated by Django 4.2.7 on 2023-11-11 23:21

from django.db import migrations, models
import gbtbk.models


class Migration(migrations.Migration):

    dependencies = [
        ('gbtbk', '0005_remove_student_user_remove_teacher_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tdp',
            field=models.ImageField(blank=True, null=True, upload_to=gbtbk.models.tdp_path),
        ),
    ]
