# Generated by Django 4.2.7 on 2023-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
